### ISSUE TITLE
white icon on grey background

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/mp#27]
see 
![icon white against grey](https://cloud.githubusercontent.com/assets/6394777/11849718/16603bc6-a3de-11e5-83d4-b1dd72865c6b.jpg)

**Comment by robmyers** [comment]
Yes this is an explicit design decision - they float otherwise (that's the reason for the grey well around the attribution blcok as well).

Without that they look like this:

![licpos](https://cloud.githubusercontent.com/assets/21746/11858464/b2f7fc7a-a416-11e5-90d8-0e2b8163b9e8.png)

Notice the poor alignment, it's even worse for single icons like BY or CC0.

The alternative was to frame the icon area that's currently white in grey.

Or we can discuss other design options. The buttons don't have this problem because they all cover the same area. @mattl?

**Comment by mattl** [comment]
black text, grey background with a 1px border in dark grey

**Comment by robmyers** [comment]
If we were to go that route would we be better off just using the buttons?

**Comment by mattl** [comment]
I'd say so, but I think @janeatcc wants the icons.

Jane, based what on what Rob said about the floating appearance, how do you want the icons to appear?

@robmyers Possible to divide the page up into col-9 and col-3 and put all the copyright info, download, etc on the right, under the image?

**Comment by janeatcc** [comment]
I think just white background is fine in that case.

**Comment by robmyers** [comment]
Keeping white background for now.
