### ISSUE TITLE
Document why someone would incorporate CC licensing into their platform

### ISSUE THREAD

**Issue by kgodey** [creativecommons/mp#55]
_This is an Outreachy contribution task. Multiple people may complete this task, it will not be closed until the Outreachy winter 2019 contribution period ends._

---
Write up basic documentation that explains why and how (in general terms) someone might implement CC licensing into their tool, website, platform, or project. Post the documentation here (or a link to it).

**Comment by treasurechristain** [comment]
Hi! I'm Amadikwa Joy an outreachy applicant and I'd really like to contribute on this task.

**Comment by Sophi-E** [comment]
Hi. I'm an Outreachy applicant and i'm interested in working on this task.

**Comment by haatifi** [comment]
Hello! I would like to work on this task. Thanks!

**Comment by kgodey** [comment]
Go ahead

**Comment by treasurechristain** [comment]
Documentation that Explains why and How to implement CC License on a site/blog.
The moment you come up something new like video, project, or journals, you have the right to include Common Creative (cc) License. CC license is used when the initiator of an idea or an author decides to give the right to modify, share and/or use a work that he/she (the initiator or an idea or an author) have created. If you decide that you want to share your work, without losing or compromising any of your rights, you have the ability to license the work to be shared through Creative Commons. It can be applied to all copyright works like websites, blog, books, movies, music, photographs, articles and others.

Things to consider when choosing your cc license
Try to put some things into consideration when choosing your CC license document. For instance: -
If you choose a CC License builder, you have the ability to restrict the location on which you want your work to be shared, for instance, you can say you want your work to be shared only in Nigeria.

Features of CC License
All adaptation of you work
Allow commercial uses of your work

Why Should Site Owners, artists, Initiator, Creator owners use CC License
Because, with the ability of sharing feature in CC License , you will be able to make your work available to higher number of audience or user; as well as, help young once like  newbies to come up with a good work of their own.

How to use CC License
In the usage of CC License there is no formal registration process. All you have to do is just to just indicate somewhere in your work that you want to or are publishing that work under CC License using any of these six licenses listed below:
Attribution (CC BY): here, the user of a work needs to credit the initiator or creator.
Attribution Share Alike (CC BY-SA): Here, the user of a work needs to credit the initiator or creator of a work, and on the other hand, the new work should or will have the same CC License.
Attribution No Derivatives (CC BY-ND): Here, the user of a work needs to credit the initiator or creator, and may not remix or adapt the original work.
Attribution Non-Commercial (CC BY-NC): Here, the user of a work needs to credit the initiator or creator, and on the other hand, the work will or may be used only for free non-commercial purposes. For that, the initiator or the creator have the right or is free to use for commercial purposes for people who needs pay for it.
Attribution Non-Commercial Share Alike (CC BY-NC-SA): Here, the user of a work needs to credit the initiator or creator, and on the other hand, the work will or may be used only for free non-commercial purposes and will have the same CC License.
Attribution Non-Commercial No Derivatives (CC BY-NC-ND)

**Comment by haatifi** [comment]
Hi @kgodey, 

Here is basic documentation for CC licensing. If you have any suggestions or comments please let me know! 
 
[CC.pdf](https://github.com/creativecommons/mp/files/3714959/CC.pdf)

**Comment by haatifi** [comment]
Hi @kgodey,

Here is basic documentation for CC licensing. If you have any suggestions or comments please let me know!

![CC](https://user-images.githubusercontent.com/10855618/66614065-85442180-eb95-11e9-9fc9-77f564381d96.jpeg)

**Comment by kgodey** [comment]
hello @treasurechristain and @haatifi – thank you for your work! this explains why an individual person should license something they make under CC, but this is not what the question is (which is our fault, it is unclear). The question is about platforms, not individual users. e.g. why should a platform such as YouTube, Vimeo, Medium, etc. implement the option for its users to apply CC licenses to content that they upload or create on that platform. For example, if I am building a new video upload platform, why should I offer my users the option to CC-license the videos that they upload there?

I hope that's clear, please let me know if you have questions.

**Comment by NicoleOliv** [comment]
https://medium.com/@aced.portgas08/why-and-how-would-you-incorporate-creative-commons-licensing-into-your-tool-website-platform-or-2c41dffa2bb1?source=friends_link&sk=52deeb667927883891ee140741b858fb 

hello, i tried this one, i did on medium and not here because i think it would seem more clear! 
i tried to explain why and how a platform would implement that, but maybe its not too clear, i'm waiting for some feedback! i have not finished yet, it's missing the explanation of the three layers of the creative commons licenses

**Comment by haatifi** [comment]
Thanks for the clarification @kgodey. I will redo the documentation!

**Comment by annatuma** [comment]
@NicoleOliv you're on the right track. As mentioned on the other task you made a contribution to, we look forward to seeing your final application for the project.

**Comment by treasurechristain** [comment]
https://medium.com/@amadikwajoyn/reasons-why-platforms-should-encourage-their-users-to-use-creative-common-license-on-their-work-dec9bd6adb56?sk=4b267f3ce2727577100b246cda633aa8

Hi @kgodey , i just published another one on my medium account. you can check it out their if you are unable to access the one i will be posting here. Waiting for feedback here. thank you

**Comment by treasurechristain** [comment]
REASONS WHY PLATFORMS SHOULD ENCOURAGE THEIR USERS TO USE CREATIVE COMMON LICENSE ON THEIR WORK

Introduction
In the world today, we have thousands of creators or producers that do come up with different creative and lovely things such as videos, articles, moves and even tutorials. But most of the issues faced by such people is the fear of copyright. Some of these people also want their work to go viral but still limits it on their dashboard. Most writer’s venture into some kind of licensing with the intention of saving their works from copywriters thereby limiting the visibility of their work.

 Why that?
Most writer understood that there are something the call licensing, but they don’t really know how to go about its usage or which licensing company they should go for. So, I think is one of the responsibilities of those platforms to educate the creators on the need of licensing their work and how the best approach to use. Licensing a work can come in lots of forms ranging from limiting copyright rate thereby reducing the usage of your work, down to, keeping your work open for other creators to recreate your work thereby allowing your work to go viral as well as acknowledging you as the original creator of that work.
Furthermore, according to the research I carried out, I discovered that almost every households uses social media to do one or two things. And the percentage of irrelevant post/video to that of relevant post/video is of the ratio 8:2. Reason is, people prefer to post more creative works in a licensed way, but not knowing that they can still post same thing in a licensed but open to copyright manner which can still acknowledge them as the right creator of such work. The licensing company that have the ability to make your work go viral and as well as acknowledges you as the original creator of such work is known as Creative Common Licensing.

What is Creative Common (CC) Licensing and how can they help your Users.
Creative Common (CC) Licensing is used when the initiator of an idea or creator decides to give other users the right to modify, share and/or use a work that he/she (the initiator or an idea or an author) have created but still get his credit as the creator.
As a platform, try to let them know that CC License is a legal internationally accepted licensing firm and explain to them the benefits of using this platform, such as the different kind/type of permissions they can integrate on their work (hence such permission do not interfere with the rules governing the licensing). And also, remind them that with the ability of sharing feature in CC License, they will be able to make their work available to higher number of audience or user; as well as, help young ones like newbies to come up with a different creative ideas from their work, thereby, giving them the credit as the creator.
In your platform, try as much as possible to put a detailed descriptions of the different things the users have to put into consideration, such as:
If a user choose a cc license builder, she/he have the ability to restrict the location on which they want their work to be shared, for instance, they can say we want our work to be shared only in Nigeria.
Also explain to them the different ways they can be able to publish their works using any of these six licensing lists:
1.	Attribution (CC BY): here, the user of a work needs to credit the initiator or creator.
2.	Attribution Share Alike (CC BY-SA): Here, the user of a work needs to credit the initiator or creator of a work, and on the other hand, the new work should or will have the same CC License.
3.	Attribution No Derivatives (CC BY-ND): Here, the user of a work needs to credit the initiator or creator, and may not remix or adapt the original work.
4.	Attribution Non-Commercial (CC BY-NC): Here, the user of a work needs to credit the initiator or creator, and on the other hand, the work will or may be used only for free non-commercial purposes. For that, the initiator or the creator have the right or is free to use for commercial purposes for people who needs pay for it.
5.	Attribution Non-Commercial Share Alike (CC BY-NC-SA): Here, the user of a work needs to credit the initiator or creator, and on the other hand, the work will or may be used only for free non-commercial purposes and will have the same CC License.
6.	Attribution Non-Commercial No Derivatives (CC BY-NC-ND)

**Comment by kgodey** [comment]
@treasurechristain thank you, this is great. hopefully the research you did for it will be useful in your final application!

**Comment by treasurechristain** [comment]
@kgodey should I go ahead with the final contribution?
And please, who is my mentor?

**Comment by kgodey** [comment]
@treasurechristain you have everything you need from Slack, right?

**Comment by treasurechristain** [comment]
@kgodey  yes, thank you. But still trying to construct my timeline very well

**Comment by kgodey** [comment]
Since the Outreachy application period is over, I'm going to close this issue.
