### ISSUE TITLE
Draft communications to platform end-users about CC licenses

### ISSUE THREAD

**Issue by kgodey** [creativecommons/mp#56]
_This is an Outreachy contribution task. Multiple people may complete this task, it will not be closed until the Outreachy winter 2019 contribution period ends._

---
Draft a set of communications that explain to platform users (not platform owners, but their “end users”) what CC is and why they might choose to use it to make their work available to the public. Post the communications (or a link to them) here.

**Comment by kgodey** [comment]
Answering a question asked on Slack: "Communications" might be emails or blog posts or any other method (up to you to decide).

**Comment by NicoleOliv** [comment]
https://medium.com/@aced.portgas08/creative-commons-not-all-the-rights-reserved-b6a2c2a94161
here's the link of mine! I've tried to make a simple contribution, it might seem too big, but i swear it isn't! I've just tried to explain everything, even the things in the graphics. 
i decide to make a questionnaire as a communication, because blog or emails seemed very difficult to me! I search for people who might be the target public of Creative Commons, and as i was asking what things to them, i was getting to make them know more about Creative Commons licensing, i put simple information's to them, as they going to answer the questions.
i hope isn't too confuse...

**Comment by WeerakoonOS** [comment]
Hi, @kgodey . I would like to contribute to this issue.  Just to clarify things here, the requirement is to create a communication medium(email/ blog posts) that explains what CC is and why a user might choose to use it to make their work available to the public?

**Comment by kgodey** [comment]
@WeerakoonOS, yes, from the perspective of a platform. for example, YouTube is a platform, you can choose to explain to YouTube users what CC is and why they should share their YouTube videos via a CC license.

**Comment by annatuma** [comment]
@NicoleOliv thank you for your creative approach to this task. The research that you carried out, documented in your blog post, is an excellent precursor to preparing communications about how users might go about applying CC-licenses to their work through a publishing platform. We look forward to seeing your final project application.

**Comment by NicoleOliv** [comment]
@annatuma oh my god@ thank you so much for you feedback! that means so much to me! please tell me if there's something that i should change or make it better

**Comment by kgodey** [comment]
Since the Outreachy application period is over, I'm going to close this issue.
